# -*- coding: utf-8 -*-
"""
Created on Mon Apr 19 16:55:35 2021

@author: Austin Schenk
"""

#Austin Schenk
#Project Euler Problem 2




#Each new term in the Fibonacci sequence is generated by adding the previous 
#two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed 
#four million, find the sum of the even-valued terms.





#import numpy as np

fib = [1,1]
even = []
odd = []
m=1000
for i in range(2,m):
    fib.append((i-1)+(i-2))
    
    if fib[i]%2 == 0:
        even.append(fib[i])
    else:
        odd.append(fib[i])
    
print(fib)




















